apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sA+SWzrJM7k4qiiTxXYWaMgqVZ8cuA7wqDlenC+PvwI=,iv:9c0p6mwb0GnbXdJSVKj3Umjxfsn9vtFGxM0tTDtN74A=,tag:WgWnrj7PcTI/Tk9zymTRJg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RbFezAXr7HHxggL/2ulXseVt7+OIp7NeQxQpb9PIHZA=,iv:o2GqphplqqPow0dZx4YVIvJGQIe+1Kte1EB4DpQqDCc=,tag:o64tcRUqCWw2mxk+2GPZFA==,type:str]
sops:
    age:
        - recipient: age1l2k984dx2876w786fuw3j5hz34k4ahuwzq8qfmjcnlk4mxvl2alqdyehmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQjlmdzRweGR2WXFNOVl3
            MUpjY3p0ZDJFNVNKaFNDY1V6NU5pU2NzVlZzCjBUdFBWcE1USVJ5MWN0MU4ybmxv
            NlBoR0dBcEhsVStkNHl2cjdEUzRlRWMKLS0tIFdOdndoVk50M2t3NnZ4dkpib0Rs
            NGErTWQxMWV4Qm96KzRtWXpVZVQ1TjAKPDSmyUcRYNcVw5IiSCzRb1nj8g5Hey0p
            lF1nNrGqZGFrO8J9Xmbb7Tg0Lah74trv/a9HCF64dF/UPGDgcJYStw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T14:38:15Z"
    mac: ENC[AES256_GCM,data:YFvqlmj79flcBLnheDhpH5joMgwm/2X0sOvcXjKARL5ulfxm6+imfwhYizu3qgdxJoJT8DyuQSaZ3evlsRAyG27cehXjTjxrkfhRnFvvKJg42xd5kE3FThU18iG/1431lDh5+0JVn9RP93qDagjF4FaK6eRFmU0eIb6C/2TcaOk=,iv:07LzajVmTsmKLpGKeI573nBnxJ4EnXXv2BftXEu9hyY=,tag:iJ/jKhYYtTgsM7bRS9nQqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
