apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PnTHowcsPK/j43bha0SebXuZzEBBOpqyEAOCOb7aPwOkjamQLXpBak0RRtM=,iv:n0S89rOVk8nrnCyf3AZ2F4TL0SEyr4guSFheBqf64d4=,tag:iAhnwOlWXkNGje9wKleTwQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1E5qYk8LsuAW//ndhqKQCgrbawNmhNURvqZRveVqpSkHgcvNySjwm+2v1mc=,iv:9krFq9VAuBCz3paEehhn+ZHaznVr2X6kbyViJEwUQpA=,tag:V6m3OUXiIhmmKTHblwGlLA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:7ZF3ZnIA0fpDg5AUEpl6mAix7R+oDLlJTdhVLQ==,iv:ZjS7Iigql8a1r6x6PCrJ/UOkumcHHsQ+vMzG2C9BCTc=,tag:0Si1J/60paw3mm6PYWvQLA==,type:str]
    S3_REGION: ENC[AES256_GCM,data:gqBEu6T8YhSSmd51,iv:lR/HNxz80RHQ2B7PR9OZMf3TohQ2mAR0RqVDqeQDo5w=,tag:TjSJq0b8bL/pwjr66LRvoQ==,type:str]
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
sops:
    age:
        - recipient: age1wr3tvh8j52xrfmyjwuxk2hrcxmggqz72evjh3m25d4s6sgm0z9lqc8nd33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOFhuTkZRcUdtdFVHVHJX
            R0k3YXhSZUE1ZnBtU0xlODY0bzgxNjlRYjJrCm0rSUs2cVpkVkNsV1hzYUZQM3NQ
            RXpKMnNYM1FZazNIdGMzWHhFR1JDajQKLS0tIDBhd0hxZU03aWtWbXkzbUNWZDZN
            UlVFRWtzbmhLV0JrMkNmb2d3YW9BYTgKYsLKewjna6BvCjsdTHyITrzcGlFYFDE2
            b827Kr2oJ+MRkME0vJ/Ed5EBHo5pRi/aE6wczj443R5xvCNW0BII5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zmwxwgtn86w8fhs28cx90nyp2r8hq9a78p6ufrcer75e9u9j5pszfndpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bkU3OEJaUWs1eVVkYXNk
            UlBqN1k2ajZTUkptellrUGk1UUt1dU0zakRnCjlkMHZ3OFl6UG1mUEZLdnJabzhX
            Zzd5bzBMNXZ5aUJ5U0cvM2N0WlRSZkUKLS0tIGpTV2Y4REdZazloUnIxaU82bEdK
            VWdLMCt0NlhJUTc1L1RNM1dEd05HeTgKXWMrCNWUjXV5EGkqjepzaQctEgtJCFWT
            EUmT05F5ek7y2gTdBXgM7ZwmyS4sVppNrgINRky+l0KKBqCzllvowQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T14:40:09Z"
    mac: ENC[AES256_GCM,data:4q3MC7cwCTrkK8vtN8Fn2fvwDdZkXUDlTBWq7g+VTMRyOCUQp63sj+iacsLGkX9X5zmL6EgX84S/P22l/t85moVEb5JX9cvjm5bSZ848vSzzAswgNyh4On1WJe8HCVTiObgHTx1ypE6SbAu61r0trR2bk/1K8WVZvfXrrqIn3d4=,iv:WXe8gcEeRRLm2QEvXt+XgiScvtRBR7fqgxY4JuM5TuI=,tag:EWkubL30RhadZBHMdg5tNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
