apiVersion: v1
kind: Secret
metadata:
  name: repo-ssh-conduction-monitoring
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:ConductionNL/monitoring.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDlLNVd6KYgY6bPHWlHer7pNhA5Zf3/6DeztsjChxRKcAAAAKhTe1r9U3ta
    /QAAAAtzc2gtZWQyNTUxOQAAACDlLNVd6KYgY6bPHWlHer7pNhA5Zf3/6DeztsjChxRKcA
    AAAEAV68/am/olwbN+EdeO24dOWT5jL0/ahl+wUwgrShRhhuUs1V3opiBjps8daUd6vuk2
    EDll/f/oN7O2yMKHFEpwAAAAHmFyZ29jZEBjb25kdWN0aW9ubmwtbW9uaXRvcmluZwECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----

