apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-sensor
  namespace: argo-events
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-runner
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: monitoring
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","get","list","watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-sensor-job-creator
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: events-sensor
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autofix-runner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","delete"]
- apiGroups: ["apps"]
  resources: ["replicasets","deployments","statefulsets"]
  verbs: ["get","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autofix-runner-binding
subjects:
- kind: ServiceAccount
  name: kubectl-runner
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autofix-runner

