prometheus:
  prometheusSpec:
    evaluationInterval: 30s
    scrapeInterval: 30s
    ruleSelector:
      matchLabels:
        release: mon
    ruleNamespaceSelector: {}
alertmanager:
  configMapOverrideName: mon-kube-prometheus-stack-alertmanager
  alertmanagerSpec:
    replicas: 2
    secrets:
    - alertmanager-slack-webhook
grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: false
    dashboards:
      enabled: true
      label: grafana_dashboard
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
