apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.5.0
    helm:
      releaseName: mon
      valueFiles:
      - $values/overlays/prod/values-prom-stack.yaml
  - repoURL: git@github.com:ConductionNL/monitoring.git
    targetRevision: main
    ref: values
  - repoURL: git@github.com:ConductionNL/monitoring.git
    targetRevision: main
    path: rules/coredns
  - repoURL: git@github.com:ConductionNL/monitoring.git
    targetRevision: main
    path: rules/pods
  - repoURL: git@github.com:ConductionNL/monitoring.git
    targetRevision: main
    path: alerting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
